### ISSUE TITLE
BenderCAM 0.9.0 not working...

### ISSUE THREAD

**Issue by beta-tester** [vilemnovak/blendercam#26]
i can't run
**blender-2.76b-linux-glibc211-x86_64_CAM_0.9.tar.gz**
nor
**blender-2.76b-linux-glibc211-i686_CAM_0.9.tar.gz**
on my Ubuntu 15.11...
blenderCAM is not available and throws exceptions to the console...

in the console, blender tells:

```
Read new prefs: /home/me/bin/blenderCAM-release/2.76/config/userpref.blend
found bundled python: /home/me/bin/blenderCAM-release/2.76/python
addon not found: 'space_view3d_screencast_keys'
addon not found: 'io_import_scene_dxf'
Traceback (most recent call last):
  File "/home/me/bin/blenderCAM-release/2.76/scripts/modules/addon_utils.py", line 324, in enable
    mod = __import__(module_name)
  File "/home/me/bin/blenderCAM-release/2.76/scripts/addons/basrelief.py", line 2, in <module>
    import numpy
  File "/home/me/.local/lib/python3.4/site-packages/numpy/__init__.py", line 201, in <module>
    from . import random
  File "/home/me/.local/lib/python3.4/site-packages/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
ImportError: /home/me/.local/lib/python3.4/site-packages/numpy/random/mtrand.cpython-34m.so: undefined symbol: PyFPE_jbuf
addon not found: 'export_svg'
addon not found: 'curve_tools'
Traceback (most recent call last):
  File "/home/me/bin/blenderCAM-release/2.76/scripts/modules/addon_utils.py", line 324, in enable
    mod = __import__(module_name)
  File "/home/me/bin/blenderCAM-release/2.76/scripts/addons/cam/__init__.py", line 34, in <module>
    from cam import ui, ops, utils, simple, polygon_utils_cam#, post_processors
  File "/home/me/bin/blenderCAM-release/2.76/scripts/addons/cam/ops.py", line 26, in <module>
    from cam import utils, pack,polygon_utils_cam,chunk,simple
  File "/home/me/bin/blenderCAM-release/2.76/scripts/addons/cam/utils.py", line 37, in <module>
    import numpy
  File "/home/me/.local/lib/python3.4/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
ImportError: cannot import name 'add_newdocs'
addon not found: 'add_mesh_pipe_joint'
addon not found: 'delaunay_voronoi'
addon not found: 'space_view3d_precise_align12'
addon not found: 'macros'
```

i can run **blender-2.70a-linux-glibc211-x86_64_CAM_0.8.0.tar.gz** is on that system successfully

**Comment by beta-tester** [comment]
fixed.
there was an collision with an "ugly" **numpy** installation.
```
rm -f ~/.local/bin/f2py3.4
rm -rf ~/.local/lib/python3.4/site-packages/numpy
```
and
`sudo apt-get -y install libgeos-3.5.0 libgeos-dev`
solved my problems finally
